apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app

    spec:
      containers:
      - name: devops-app
        image: goravasiva/devops-flask-app:5942b41288b3d2ec634ebe5c6d0a6a0f68b6ffde
        ports:
        - containerPort: 5000