apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app

    spec:
      containers:
      - name: devops-app
        image: goravasiva/devops-flask-app:377ff78cadd2ee61acb952869ba4d9faa3ac8c46
        ports:
        - containerPort: 5000