apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app

    spec:
      containers:
      - name: devops-app
        image: goravasiva/devops-flask-app:b2beb7cc77b4b75cd1a667c2cfd09a0576c5c72f
        ports:
        - containerPort: 5000